# Generated by Django 5.1 on 2024-12-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchresponsedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresponsedata',
            name='estimate_reference_id',
            field=models.CharField(default='111000021', max_length=20),
            preserve_default=False,
        ),
    ]
