# Generated by Django 5.1 on 2024-11-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription_last_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='renewal_date',
        ),
    ]
