# Generated by Django 5.1 on 2024-12-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_searchresponsedata_estimate_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresponsedata',
            name='saved_response_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
