# Generated by Django 5.1 on 2024-08-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscription_token_allocation_stripeprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_token_allocation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
