# Generated by Django 5.1 on 2024-11-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_subscription_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_pending',
            field=models.BooleanField(default=False),
        ),
    ]
