# Generated by Django 5.1 on 2024-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription_cancellation_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_processed_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
