# Generated by Django 5.1 on 2024-11-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscription_last_processed_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='username',
            field=models.CharField(default='temp_username', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
