# Generated by Django 5.1.4 on 2025-01-02 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscription_trial_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
