# Generated by Django 5.1 on 2024-09-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stripeprofile_is_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
