# Generated by Django 5.1 on 2024-11-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='username',
        ),
    ]
