# Generated by Django 5.1 on 2024-09-12 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_subscription_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientData', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimateitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimateItems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userestimates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userEstimates', to=settings.AUTH_USER_MODEL),
        ),
    ]
