# Generated by Django 5.1.4 on 2025-01-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_emailchangehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_account_OAuth',
            field=models.BooleanField(default=False),
        ),
    ]
