# Generated by Django 5.1 on 2024-10-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_estimateitems_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userestimates',
            name='id',
        ),
        migrations.AlterField(
            model_name='userestimates',
            name='estimate_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
