name: Deploy to AWS Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and run update script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Adding EC2 SSH key"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Connecting to EC2..."
          ssh -o ForwardAgent=yes -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_ed25519
            cd /home/ubuntu/estimator/scripts
            ./update_deploy.sh
          EOF



