name: Test AppSpec and Deployment Scripts

on:
  pull_request:
    branches:
      - Dev
      - Prod
  push:
    branches:
      - Dev
      - Prod

jobs:
  validate-appspec:
    name: Validate appspec.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 to support Node 16 and 20

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4 for Node 16 and 20 support
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint on appspec.yml
        run: yamllint appspec.yml

  test-deployment-scripts:
    name: Test Deployment Scripts
    runs-on: ubuntu-latest
    needs: validate-appspec
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set executable permissions for scripts
        run: chmod +x scripts/*.sh

      - name: Run stop_server script
        run: |
          if [ -f scripts/stop_server.sh ]; then
            bash scripts/stop_server.sh
          fi

      - name: Run install_dependencies script
        run: |
          if [ -f scripts/install_dependencies.sh ]; then
            bash scripts/install_dependencies.sh
          fi

      - name: Run build_frontend script
        run: |
          if [ -f scripts/build_frontend.sh ]; then
            bash scripts/build_frontend.sh
          fi

      - name: Run start_server script
        run: |
          if [ -f scripts/start_server.sh ]; then
            bash scripts/start_server.sh
          fi

      - name: Run validate_service script
        run: |
          if [ -f scripts/validate_service.sh ]; then
            bash scripts/validate_service.sh
          fi

